sinaisblaze/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sitesinais.urls')),  # inclui os links do aplicativo ao diretorio '/'
]

sitesinais/urls.py
from django.urls import path

from sitesinais import views

app_name = 'sitesinais'

urlpatterns = [
    path('', views.home, name="home"),
    path('cadastro/', views.cadastro, name="cadastro"),
    path('my-page/', views.trial, name="trial"),
    path('confirmacao/', views.confirmacao, name="confirmacao"),
    path('logout/', views.logout_view, name="logout"),
    path('api-last-14/', views.get_last_results, name="get_last_results"),
]

sitesinais/models.py
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None, whatsapp_number=None, referal=None):
        if not email:
            raise ValueError('Insira um email!')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            whatsapp_number=whatsapp_number,
            referal=referal
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password=None, whatsapp_number=None, referal=None):
        user = self.create_user(
            email=email,
            first_name=first_name,
            last_name=last_name,
            password=password,
            whatsapp_number=whatsapp_number,
            referal=referal
        )

        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


# Modelo de Tabela Customizada pro projeto!


class CustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    whatsapp_number = models.CharField(max_length=20, blank=True, null=True)
    referal = models.CharField(max_length=50, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    confirmation = models.IntegerField(blank=True, null=True)
    # campo na tabela para fazer a confirmação do cadastro!
    is_trusty = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'  # email como chave primaria para login
    # campos que são obrigatorios para cadastro junto com a chave primaria
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.email


class Dados(models.Model):
    number = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    background = models.CharField(max_length=255)

    class Meta:
        db_table = 'dados'


class Sinais(models.Model):
    status = models.CharField(max_length=255, blank=True, null=True)
    background = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'sinais'

sitesinais/forms.py
from django import forms
from django.forms import ModelForm, ValidationError

from .models import CustomUser


class CadastroForm(ModelForm):

    class Meta:
        model = CustomUser
        fields = [
            'first_name',
            'last_name',
            'whatsapp_number',
            'email',
            'referal',
            'password',
        ]

        labels = {
            'first_name': '',
            'last_name': '',
            'whatsapp_number': '',
            'email': '',
            'referal': '',
            'password': '',
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'Nome'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Sobrenome'}),
            'whatsapp_number': forms.NumberInput(attrs={'placeholder': 'Whatsapp'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email'}),
            'referal': forms.TextInput(attrs={'placeholder': 'Codigo Indicação'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Senha'})
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if CustomUser.objects.filter(email=email).exists():
            raise ValidationError('Já existe um usuário com este email.')
        return email

sitesinais/views.py
import random

import pusher
from decouple import config
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string

from .forms import CadastroForm
from .models import CustomUser, Dados


def home(request):
    apear_login = True
    if request.user.is_authenticated:
        return redirect('/my-page/')

    elif request.method == "GET":
        return render(request, 'sitesinais/pages/index.html',
                      {'apear_login': apear_login})
    else:
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)

        if user:
            activate = CustomUser.objects.get(email=email)
            activate = activate.is_trusty
            if activate is not False:
                login(request, user)
                return redirect('/my-page/')
            else:
                request.session['confirm_email'] = email
                return redirect('/confirmacao/')
        else:
            messages.error(request, 'Email e/ou Senha inválidos')
            return render(request, 'sitesinais/pages/index.html',
                          {'apear_login': apear_login})


def cadastro(request):
    apear_register = True
    form = CadastroForm()
    #  verifica se o usuario ja esta authenticado e tenta acessar a pagina cadastro
    if request.user.is_authenticated:
        return redirect('/my-page/')
    # verifica se o methodo da pagina é GET para renderizar o template
    if request.method == "GET":
        return render(request, 'sitesinais/pages/cadastro.html',
                      {'form': form,
                       'apear_register': apear_register})
    #  se o methodo for POST entra no else
    else:
        form = CadastroForm(request.POST)
        #  verifica se o formulario é valido ao que pede no forms.CustomUser
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.confirmation = random.randint(100000, 999999)
            user.save()
            email = user.email
            confirmation = user.confirmation
            message = f'Código de Ativação: {confirmation}'
            from_email = config('EMAIL_HOST_USER')
            send_mail(subject='Cadastro',
                      message=message,
                      from_email=from_email,
                      recipient_list=[email])
            request.session['confirm_email'] = email

            return redirect('/confirmacao/')
        #  se não for valido renderiza novamente o template porem mostra os erros!
        else:
            return render(request, 'sitesinais/pages/cadastro.html',
                          {'form': form,
                           'apear_register': apear_register, })


def confirmacao(request):
    apear_register = True
    if request.user.is_authenticated:
        return redirect('/my-page/')
    email = request.session.get('confirm_email')
    if request.method == 'GET':
        return render(request, 'sitesinais/pages/confirmacao.html',
                      {'apear_register': apear_register})
    else:
        if email:
            user = CustomUser.objects.get(email=email)
            cod = int(request.POST.get('cod-confirm'))
            if int(user.confirmation) != cod:
                messages.error(request, 'Código incorreto!')
                return render(request, 'sitesinais/pages/confirmacao.html',
                              {'apear_register': apear_register})
            else:
                user.is_trusty = True
                user.save()
                return redirect('/')


@login_required(login_url='/')
def trial(request):
    apear_button = True
    results = Dados.objects.order_by(
        '-id')[:14].values('number', 'date', 'background')
    results_white = Dados.objects.filter(background=';')
    quant_white = results_white.count()
    results_red = Dados.objects.filter(background='#CD1010;')
    quant_red = results_red.count()
    results_black = Dados.objects.filter(background='black;')
    quant_black = results_black.count()
    context = {'results': results,
               'white': quant_white,
               'red': quant_red,
               'black': quant_black,
               }
    return render(request, 'sitesinais/pages/trial.html',
                  context=context,
                  )


def logout_view(request):
    logout(request)
    return redirect('/')


def get_last_results(request):
    results = Dados.objects.order_by(
        '-id')[:14].values('number', 'date', 'background')
    html = render_to_string(
        'sitesinais/partials/dashboard/latest_results.html', {'results': results})
    return HttpResponse(html)

sitesinais/templates/sitesinais/pages/cadastro.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>

    {% include 'sitesinais/partials/head.html' %}
    <title>{% block title %}Cadastro {% endblock %}| TiroCerto</title>

</head>

<body>
    <section class="container">

        {% include 'sitesinais/partials/header.html' %}

        <section class="information">
            <div class="information-hidden">
                <div class="information-title">
                    <h2>Acertos do Bot:</h2>
                </div>
                <div class="information-bar">
                    <div class="progress">
                        <div class="progress-in" style="width: 91.50%;"></div>
                        <div class="porcent">91.50%</div>
                    </div>
                </div>
                <div class="information-sub">
                    <h4>9 acertos a cada 10 Jogadas</h4>
                    <h4 class="green">4 a cada 5 Jogadas Certas</h4>
                    <h4><span class="green" style="font-size: 24px;">189</span> Acertos HOJE!</h4>
                    <h5>Todos dados resetam as 00:00 (Horário de Brasilia)</h5>
                    <h5>Dados são Atualizados a cada 10 minutos</h5>
                </div>
            </div>
            <div class="login-content">
                <div class="login">
                    <div class="user-online"><span class="members red">243</span> Apostadores <span
                            class="green">Online</span>
                    </div>
                    {% include 'sitesinais/partials/form-register.html' %}
                </div>
            </div>
        </section>

        {% include 'sitesinais/partials/footer.html' %}
        
    </section>
</body>

</html>

sitesinais/templates/sitesinais/pages/confirmacao.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>

    {% include 'sitesinais/partials/head.html' %}
    <title>{% block title %}Login {% endblock %}| TiroCerto</title>
    
</head>

<body>
    <section class="container">

        {% include 'sitesinais/partials/header.html' %}

        <section class="information">
            <div class="information-hidden">
                <div class="information-title">
                    <h2>Acertos do Bot:</h2>
                </div>
                <div class="information-bar">
                    <div class="progress">
                        <div class="progress-in" style="width: 91.50%;"></div>
                        <div class="porcent">91.50%</div>
                    </div>
                </div>
                <div class="information-sub">
                    <h4>9 acertos a cada 10 Jogadas</h4>
                    <h4 class="green">4 a cada 5 Jogadas Certas</h4>
                    <h4><span class="green" style="font-size: 24px;">189</span> Acertos HOJE!</h4>
                    <h5>Todos dados resetam as 00:00 (Horário de Brasilia)</h5>
                    <h5>Dados são Atualizados a cada 10 minutos</h5>
                </div>
            </div>
            <div class="login-content">
                <div class="login">
                    <div class="user-online"><span class="members red">243</span> Apostadores <span
                            class="green">Online</span>
                    </div>
                    <form action="{% url 'sitesinais:confirmacao' %}" method="POST">{% csrf_token %}
                        <div class="text-input">
                            <input id="cod-confirm" name="cod-confirm" class="input" type="number" placeholder="Codigo enviado no Email" required>
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="error-message">{{ message }}</div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <button class="btn-login" type="submit">Confirmar</button>
                    </form>
                </div>
            </div>
        </section>

        {% include 'sitesinais/partials/footer.html' %}

    </section>
</body>

</html>

sitesinais/templates/sitesinais/pages/index.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>

    {% include 'sitesinais/partials/head.html' %}
    <title>{% block title %}Login {% endblock %}| TiroCerto</title>

</head>

<body>
    <section class="container">

        {% include 'sitesinais/partials/header.html' %}

        <section class="information">
            <div class="information-hidden">
                <div class="information-title">
                    <h2>Acertos do Bot:</h2>
                </div>
                <div class="information-bar">
                    <div class="progress">
                        <div class="progress-in" style="width: 91.50%;"></div>
                        <div class="porcent">91.50%</div>
                    </div>
                </div>
                <div class="information-sub">
                    <h4>9 acertos a cada 10 Jogadas</h4>
                </div>
            </div>
            <div class="login-content">
                <div class="login">
                    {% include 'sitesinais/partials/form-login.html' %}
                </div>
            </div>
        </section>

        {% include 'sitesinais/partials/footer.html' %}

    </section>
</body>

</html>

sitesinais/templates/sitesinais/pages/trial.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>

    {% include 'sitesinais/partials/head.html' %}
    <title>{% block title %}Sinais {% endblock %}| TiroCerto</title>

</head>

<body>
    <section class="container">
        <section class="container-header">
            <div class="logo"><a>Tiro Certo</a></div>
            <div class="sinais-title">
                <h2>Sinais<span>On</span>line</h2>
            </div>
                <div class="buttons">
                    <form action="{% url 'sitesinais:logout' %}" method="POST">{% csrf_token %}
                        <button class="btn-login logout" type="submit">Sair</button>
                    </form>
                    <div class="btn-register" style="display:None;">
                        <a href="{% url 'sitesinais:cadastro' %}">Comprar Acesso</a>
                    </div>
                </div>
        </section>
        <div class="row"></div>
        <div class="moves-content">
            <div class="moves" id="results-container">
                {% include 'sitesinais/partials/dashboard/latest_results.html' %}
            </div>
        </div>
        <section class="trial-content">
            <div class="row"></div>
            <div class="trial-page">
                {% include 'sitesinais/partials/dashboard/signals.html' %}
                {% include 'sitesinais/partials/dashboard/result.html' %}
            </div>
        </section>
        {% include 'sitesinais/partials/footer.html' %}
        
    </section>
</body>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://js.pusher.com/7.0/pusher.min.js"></script>
    <script>
        // Enable pusher logging - don't include this in production
        Pusher.logToConsole = true;

        var pusher = new Pusher('9652881ff8a799315f76', {
        cluster: 'sa1'
        });

        var channel = pusher.subscribe('sitesinais');
        channel.bind('sinaispage', function(data) {
            console.log(data); // vai pro console os dados da variavel data que vem do backend
            var last_14 = data.last_14; //dados da variavel data que a chave se chama last_14 podendo ter mais keys em data
            var html = '';
            for (var i = 0; i < last_14.length; i++) {
                var item = last_14[i];
                var background = item.background;
                var number = item.number;
                html += '<div id="box" class="move square" style="background: ' + background + '">';
                html += '<div class="icon-1">' + number + '</div>';
                html += '</div>';
            }
            $('#results-container').html(html); // atualiza o conteudo do id results-container
        });

        channel.bind('sinaisbot', function(data) {
            console.log(data);
            var h1Value = data.h1;
            var backgroundValue = data.background;
            var dateValue = data.date;

            document.getElementById('h1-sinais').innerHTML = h1Value;
            var boxStyle = document.getElementById('box-sinais')
            boxStyle.style.backgroundColor = backgroundValue;
            document.getElementById('h2-sinais').innerHTML = dateValue;
        })
    </script>
</html>