sinaisblaze/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sitesinais.urls')),  # inclui os links do aplicativo ao diretorio '/'
]

sitesinais/urls.py
from django.urls import path

from sitesinais import views

app_name = 'sitesinais'

urlpatterns = [
    path('', views.home, name="home"),
    path('cadastro/', views.cadastro, name="cadastro"),
    path('my-page/', views.trial, name="trial"),
    path('confirmacao/', views.confirmacao, name="confirmacao"),
    path('logout/', views.logout_view, name="logout"),
    path('api-last-14/', views.get_last_results, name="get_last_results"),
]

sitesinais/models.py
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None, whatsapp_number=None, referal=None):
        if not email:
            raise ValueError('Insira um email!')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            whatsapp_number=whatsapp_number,
            referal=referal
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password=None, whatsapp_number=None, referal=None):
        user = self.create_user(
            email=email,
            first_name=first_name,
            last_name=last_name,
            password=password,
            whatsapp_number=whatsapp_number,
            referal=referal
        )

        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


# Modelo de Tabela Customizada pro projeto!


class CustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    whatsapp_number = models.CharField(max_length=20, blank=True, null=True)
    referal = models.CharField(max_length=50, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    confirmation = models.IntegerField(blank=True, null=True)
    # campo na tabela para fazer a confirmação do cadastro!
    is_trusty = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'  # email como chave primaria para login
    # campos que são obrigatorios para cadastro junto com a chave primaria
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.email


class Dados(models.Model):
    number = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    background = models.CharField(max_length=255)

    class Meta:
        db_table = 'dados'


class Sinais(models.Model):
    status = models.CharField(max_length=255, blank=True, null=True)
    background = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'sinais'

sitesinais/forms.py
from django import forms
from django.forms import ModelForm, ValidationError

from .models import CustomUser


class CadastroForm(ModelForm):

    class Meta:
        model = CustomUser
        fields = [
            'first_name',
            'last_name',
            'whatsapp_number',
            'email',
            'referal',
            'password',
        ]

        labels = {
            'first_name': '',
            'last_name': '',
            'whatsapp_number': '',
            'email': '',
            'referal': '',
            'password': '',
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'Nome'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Sobrenome'}),
            'whatsapp_number': forms.NumberInput(attrs={'placeholder': 'Whatsapp'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email'}),
            'referal': forms.TextInput(attrs={'placeholder': 'Codigo Indicação'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Senha'})
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if CustomUser.objects.filter(email=email).exists():
            raise ValidationError('Já existe um usuário com este email.')
        return email

sitesinais/views.py
import random

import pusher
from decouple import config
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string

from .forms import CadastroForm
from .models import CustomUser, Dados


def home(request):
    apear_login = True
    if request.user.is_authenticated:
        return redirect('/my-page/')

    elif request.method == "GET":
        return render(request, 'sitesinais/pages/index.html',
                      {'apear_login': apear_login})
    else:
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)

        if user:
            activate = CustomUser.objects.get(email=email)
            activate = activate.is_trusty
            if activate is not False:
                login(request, user)
                return redirect('/my-page/')
            else:
                request.session['confirm_email'] = email
                return redirect('/confirmacao/')
        else:
            messages.error(request, 'Email e/ou Senha inválidos')
            return render(request, 'sitesinais/pages/index.html',
                          {'apear_login': apear_login})


def cadastro(request):
    apear_register = True
    form = CadastroForm()
    #  verifica se o usuario ja esta authenticado e tenta acessar a pagina cadastro
    if request.user.is_authenticated:
        return redirect('/my-page/')
    # verifica se o methodo da pagina é GET para renderizar o template
    if request.method == "GET":
        return render(request, 'sitesinais/pages/cadastro.html',
                      {'form': form,
                       'apear_register': apear_register})
    #  se o methodo for POST entra no else
    else:
        form = CadastroForm(request.POST)
        #  verifica se o formulario é valido ao que pede no forms.CustomUser
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.confirmation = random.randint(100000, 999999)
            user.save()
            email = user.email
            confirmation = user.confirmation
            message = f'Código de Ativação: {confirmation}'
            from_email = config('EMAIL_HOST_USER')
            send_mail(subject='Cadastro',
                      message=message,
                      from_email=from_email,
                      recipient_list=[email])
            request.session['confirm_email'] = email

            return redirect('/confirmacao/')
        #  se não for valido renderiza novamente o template porem mostra os erros!
        else:
            return render(request, 'sitesinais/pages/cadastro.html',
                          {'form': form,
                           'apear_register': apear_register, })


def confirmacao(request):
    apear_register = True
    if request.user.is_authenticated:
        return redirect('/my-page/')
    email = request.session.get('confirm_email')
    if request.method == 'GET':
        return render(request, 'sitesinais/pages/confirmacao.html',
                      {'apear_register': apear_register})
    else:
        if email:
            user = CustomUser.objects.get(email=email)
            cod = int(request.POST.get('cod-confirm'))
            if int(user.confirmation) != cod:
                messages.error(request, 'Código incorreto!')
                return render(request, 'sitesinais/pages/confirmacao.html',
                              {'apear_register': apear_register})
            else:
                user.is_trusty = True
                user.save()
                return redirect('/')


@login_required(login_url='/')
def trial(request):
    apear_button = True
    results = Dados.objects.order_by(
        '-id')[:14].values('number', 'date', 'background')
    results_white = Dados.objects.filter(background=';')
    quant_white = results_white.count()
    results_red = Dados.objects.filter(background='#CD1010;')
    quant_red = results_red.count()
    results_black = Dados.objects.filter(background='black;')
    quant_black = results_black.count()
    context = {'results': results,
               'white': quant_white,
               'red': quant_red,
               'black': quant_black,
               }
    return render(request, 'sitesinais/pages/trial.html',
                  context=context,
                  )


def logout_view(request):
    logout(request)
    return redirect('/')


def get_last_results(request):
    results = Dados.objects.order_by(
        '-id')[:14].values('number', 'date', 'background')
    html = render_to_string(
        'sitesinais/partials/dashboard/latest_results.html', {'results': results})
    return HttpResponse(html)

sitesinais/templates/sitesinais/partials/footer.html
<div class="row"></div>
<footer class="main-footer">
    <div class="developer">
        <a href="http://thiagocosta.site/" target="_blank" rel="noreferrer">Thiago Costa</a>
    </div>
        
    <div class="powered">
        <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer">Powered by Django</a>
    </div>
</footer>

sitesinais/templates/sitesinais/partials/form-login.html
<form action="{% url 'sitesinais:home' %}" method="POST">{% csrf_token %}
    <div class="text-input">Email:
        <input name="email" class="input" type="text" placeholder="Email" required>
    </div>
    <div class="text-input">Senha:
        <input name="password" class="input" type="password" placeholder="Senha" required>
        {% if messages %}
            {% for message in messages %}
                <div class="error-message">{{ message }}</div>
            {% endfor %}
        {% endif %}
    </div>
    <button class="btn-login-home" type="submit">Entrar</button>
</form>

sitesinais/templates/sitesinais/partials/form-register.html
<form action="{% url 'sitesinais:cadastro' %}" method="POST">{% csrf_token %}
    <div class="text-input">
        {{ form.first_name }}
        {% if form.first_name.errors %}
            <div class="error-message">
                {% for error in form.first_name.errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <div class="text-input">
        {{ form.last_name }}
        {% if form.last_name.errors %}
            <div class="error-message">
                {% for error in form.last_name.errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <div class="text-input">
        {{ form.whatsapp_number }}
        {% if form.whatsapp_number.errors %}
            <div class="error-message">
                {% for error in form.whatsapp_number.errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <div class="text-input">
        {{ form.email }}
        {% if form.email.errors %}
            <div class="error-message">
                {% for error in form.email.errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <div class="text-input">
        {{ form.referal }}
        {% if form.referal.errors %}
            <div class="error-message">
                {% for error in form.referal.errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <div class="text-input">
        {{ form.password }}
        {% if form.password.errors %}
            <div class="error-message">
                {% for error in form.password.errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <button class="btn-login" type="submit" href="">Cadastrar</button>
</form>

sitesinais/templates/sitesinais/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'sitesinais/css/style.css' %}">

sitesinais/templates/sitesinais/partials/header.html
<section class="container-header">
    <div class="logo"><a>Tiro Certo</a></div>
    <div class="sinais-title">
        <h2>Sinais<span>On</span>line</h2>
    </div>
    {% if not apear_button %}
        <div class="buttons">
            {% if not apear_login %}
            <div class="btn-login"><a class="login" href="{% url 'sitesinais:trial' %}">Entrar</a></div>
            {% endif %}

            {% if not apear_register %}
                <div class="btn-register"><a href="{% url 'sitesinais:cadastro' %}">Cadastrar</a></div>
            {% endif %}
        </div>
    {% else %}
        <div class="buttons">
            <form action="{% url 'sitesinais:logout' %}" method="POST">{% csrf_token %}
                <button class="btn-login logout" type="submit">Sair</button>
            </form>
            <div class="btn-register" style="display:None;">
                <a href="{% url 'sitesinais:cadastro' %}">Comprar Acesso</a>
            </div>
        </div>
        
    {% endif %}
</section>
<div class="row"></div>